name: jobs_af
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1

  url_launcher: ^6.1.12
  simple_animations: ^5.2.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.2
  iconly: ^1.0.1
  smooth_page_indicator: ^1.2.1
  lottie: ^3.1.2
  dropdown_button2: ^2.3.8

  # best icon packages .... =====
  enefty_icons: ^1.0.8
  drop_down_list: ^2.0.0
  flutter_expanded_tile: ^0.4.0
  tap_to_expand: ^0.7.2
  flutter_svg: ^2.2.1
  hugeicons: ^0.0.9
  flutter_dotenv: ^5.2.1
  iconsax: ^0.0.8
  get: ^4.6.5
  get_storage: ^2.1.1
  animated_theme_switcher: ^2.0.10
  connectivity_plus: ^7.0.0
  go_router: ^7.0.0
  # Product Specific
  carousel_slider: ^5.0.0
  readmore: ^2.2.0

  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/logo/
    - assets/fonts/
    - assets/images/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/

  fonts:
    - family: IRANSansX
      fonts:
        - asset: assets/fonts/irasans/IRANSansX-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/irasans/IRANSansX-Bold.ttf
          weight: 800
        - asset: assets/fonts/irasans/IRANSansX-Medium.ttf
          weight: 700
        - asset: assets/fonts/irasans/IRANSansX-Heavy.ttf
          weight: 600
        - asset: assets/fonts/irasans/IRANSansX-Light.ttf
          weight: 500
        - asset: assets/fonts/irasans/IRANSansX-Regular.ttf
          weight: 400
        - asset: assets/fonts/irasans/IRANSansX-Thin.ttf
          weight: 300
        - asset: assets/fonts/irasans/IRANSansX-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/irasans/IRANSansX-Thin.ttf
          weight: 100
    - family: Arabic
      fonts:
        - asset: assets/fonts/Arabic.ttf
    - family: Estedad
      fonts:
        - asset: assets/fonts/Estedad-Bold.ttf
        - asset: assets/fonts/Estedad-Black.ttf
        - asset: assets/fonts/Estedad-ExtraBold.ttf
        - asset: assets/fonts/Estedad-ExtraLight.ttf
        - asset: assets/fonts/Estedad-Light.ttf
        - asset: assets/fonts/Estedad-Medium.ttf
        - asset: assets/fonts/Estedad-Regular.ttf
        - asset: assets/fonts/Estedad-SemiBold.ttf
        - asset: assets/fonts/Estedad-Thin.ttf



flutter_native_splash:
  color: "###147efb"
  image: "assets/icons/brands/logo.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true
  android_12:
    image: "assets/icons/brands/native_splash.png"
    color: "###147efb"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/brands/logo.png"

